# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2


jobs:
  build:
    docker:
      - image:  circleci/ruby:2.4.6
    working_directory: ~/docker-rails
    steps:
      - checkout:
          path: ~/docker-rails
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby2.4.6
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_ENV: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/docker-rails
    steps:
      - checkout:
          path: ~/docker-rails
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rake test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build